tasks:
  - init: |
      curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && sudo mv wp-cli.phar /usr/local/bin/wp && pnpm add -g pnpm

vscode:
  extensions:
    - ms-azuretools.vscode-docker