name: WP & WC Compatibility Test & Auto-Bump

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: wordpress:php8.3-fpm
      env:
        WORDPRESS_DB_HOST: mysql
        WORDPRESS_DB_USER: wpuser
        WORDPRESS_DB_PASSWORD: wppass
        WORDPRESS_DB_NAME: wordpress
      options: --user root

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - /__w/vida/vida/mysql-certs:/etc/mysql/certs
          - /__w/vida/vida/mysql-conf.d:/etc/mysql/conf.d

    strategy:
      matrix:
        wordpress-version: [6.4, 6.5, latest]
        woocommerce-version: [8.8.2, latest]
        php-version: [8.3, 8.4]

    name: WP ${{ matrix.wordpress-version }} / WC ${{ matrix.woocommerce-version }} / PHP ${{ matrix.php-version }}

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git unzip rsync default-mysql-client openssl less

      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Generate SSL certificates for MySQL
        run: |
          mkdir -p /__w/vida/vida/mysql-certs
          cd /__w/vida/vida/mysql-certs

          # Generate CA
          openssl genrsa 2048 > ca-key.pem
          openssl req -new -x509 -nodes -days 3650 -key ca-key.pem -subj "/CN=MySQLTestCA" > ca.pem

          # Server cert
          openssl genrsa 2048 > server-key.pem
          openssl req -new -key server-key.pem -subj "/CN=localhost" > server-req.pem
          openssl x509 -req -in server-req.pem -days 3650 -CA ca.pem -CAkey ca-key.pem -set_serial 01 > server-cert.pem

          # Client cert
          openssl genrsa 2048 > client-key.pem
          openssl req -new -key client-key.pem -subj "/CN=client" > client-req.pem
          openssl x509 -req -in client-req.pem -days 3650 -CA ca.pem -CAkey ca-key.pem -set_serial 01 > client-cert.pem

          chmod 644 *.pem

      - name: Configure MySQL server SSL
        run: |
          mkdir -p /__w/vida/vida/mysql-conf.d
          cat > /__w/vida/vida/mysql-conf.d/ssl.cnf <<EOF
          [mysqld]
          ssl-ca=/etc/mysql/certs/ca.pem
          ssl-cert=/etc/mysql/certs/server-cert.pem
          ssl-key=/etc/mysql/certs/server-key.pem
          require_secure_transport=ON
          EOF

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h mysql -uroot -proot --ssl-ca=/__w/vida/vida/mysql-certs/ca.pem && break
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: Create MySQL user with SSL requirement
        run: |
          mysql -h mysql -uroot -proot --ssl-ca=/__w/vida/vida/mysql-certs/ca.pem <<-EOSQL
            CREATE USER IF NOT EXISTS 'wpuser'@'%' IDENTIFIED BY 'wppass' REQUIRE SSL;
            GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'%';
            FLUSH PRIVILEGES;
          EOSQL

      - name: Setup PHP tools
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp

      - name: Increase PHP memory limit
        run: echo "memory_limit = 512M" > /usr/local/etc/php/conf.d/memory-limit.ini

      - name: Create MySQL client config with SSL
        run: |
          echo "[client]" > /__w/vida/vida/my.cnf
          echo "user=wpuser" >> /__w/vida/vida/my.cnf
          echo "password=wppass" >> /__w/vida/vida/my.cnf
          echo "host=mysql" >> /__w/vida/vida/my.cnf
          echo "ssl-ca=/__w/vida/vida/mysql-certs/ca.pem" >> /__w/vida/vida/my.cnf
          echo "ssl-cert=/__w/vida/vida/mysql-certs/client-cert.pem" >> /__w/vida/vida/my.cnf
          echo "ssl-key=/__w/vida/vida/mysql-certs/client-key.pem" >> /__w/vida/vida/my.cnf
          chmod 600 /__w/vida/vida/my.cnf

      - name: Install WordPress
        run: |
          wp core download --version=${{ matrix.wordpress-version }} --path=wp --allow-root
          wp config create \
            --dbname=wordpress \
            --dbuser=wpuser \
            --dbpass=wppass \
            --dbhost=mysql \
            --path=wp \
            --allow-root

          # Force wp-cli to use SSL config
          sed -i "/require_once ABSPATH . 'wp-settings.php';/i define('WP_CLI_DB_ARGS', array('--defaults-extra-file=\/__w\/vida\/vida\/my.cnf'));" wp/wp-config.php

          wp db create --path=wp --allow-root
          wp core install \
            --url="http://localhost" \
            --title="Test Site" \
            --admin_user="admin" \
            --admin_password="password" \
            --admin_email="admin@example.com" \
            --path=wp \
            --allow-root

      - name: Install WooCommerce
        run: |
          wp plugin install woocommerce --version=${{ matrix.woocommerce-version }} --activate --path=wp

      - name: Install Plugin
        run: |
          mkdir -p wp/wp-content/plugins/vida
          rsync -av --exclude='.git*' --exclude='wp' --exclude='.github' ./ wp/wp-content/plugins/vida/
          wp plugin activate vida --path=wp

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: echo 'All tests passed.'

      - name: Bump versions in files
        if: github.ref == 'refs/heads/main' && ${{ matrix.wordpress-version == 'latest' && matrix.woocommerce-version == 'latest' && matrix.php-version == '8.3' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WP_VER=$(wp core version --path=wp --allow-root)
          WC_VER=$(wp plugin get woocommerce --field=version --path=wp --allow-root)

          echo "Bumping WP tested up to: $WP_VER"
          echo "Bumping WC tested up to: $WC_VER"

          # Update readme.txt
          sed -i "s/^Tested up to:.*/Tested up to: $WP_VER/" readme.txt

          # Update vida.php header
          sed -i "s/^\(\s*\*\s*WC tested up to:\s*\).*/\1$WC_VER/" vida.php

          # Commit and push changes
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add readme.txt vida.php

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Bump Tested up to (WP $WP_VER) and WC tested up to ($WC_VER)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
